# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "dynamic_mailer.Payload" do
    optional :reference_uuid, :string, 1
    optional :event, :string, 2
    optional :email, :string, 3
  end
  add_message "dynamic_mailer.Response" do
    optional :status, :int32, 1
  end
end

module DynamicMailer
  Payload = Google::Protobuf::DescriptorPool.generated_pool.lookup("dynamic_mailer.Payload").msgclass
  Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("dynamic_mailer.Response").msgclass
end
