# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: message.proto for package 'dynamic_mailer'

require 'grpc'

module DynamicMailer
  module Messages
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'dynamic_mailer.Messages'

      rpc :SendIt, Payload, Response
    end

    Stub = Service.rpc_stub_class
  end
end
